
data class Post(
    val id: Int,
    val ownerId: Long,
    val fromId: Long,
    val createdBy: Long,
    val date: Int,
    val text: String,
    val replyOwnerId: Long,
    val replyPostId: Long,
    val friendsOnly: Int,
    val comments: String,
    val copyright: String,
    val likes: Int,
    val reposts: String,
    val views: String,
    val postType: String,
    val signerId: Long,
    val canPin: Boolean,
    val canDelete: Boolean,
    val canEdit: Boolean,
    val isPinned: Boolean,
    val markedAsAds: Boolean,
    val isFavorite: Boolean,
    val postponedId:Int)
